/**
 * Created by HarryLee on 2017/6/15.
 */


export const buttonList = {
  training_parts:{
    title:'训练部位',
    details:{
      training_parts:{
        title:'',
        buttons:[
          {
            id:100,
            value:'不限部位'
          },
          {
            id:101,
            value:'胸部'
          },
          {
            id:102,
            value:'肩部'
          },
          {
            id:103,
            value:'背部'
          },
          {
            id:104,
            value:'手臂'
          },
          {
            id:105,
            value:'腹部'
          },
          {
            id:106,
            value:'臀部'
          },
          {
            id:107,
            value:'腿部'
          },
          {
            id:108,
            value:'全身综合'
          }
        ]
      }
    }
  },
  equipment_demand:{
    title:'器械需求',
    details:{
      free_appliance:{
        title:'自由器械',
        buttons:[
          {
            id:200,
            value:'全部'
          },
          {
            id:201,
            value:'哑铃'
          },
          {
            id:202,
            value:'杠铃'
          },
          {
            id:203,
            value:'壶铃'
          },
          {
            id:204,
            value:'弹力带'
          },
          {
            id:205,
            value:'TRX绳'
          },
          {
            id:206,
            value:'战绳'
          },
          {
            id:207,
            value:'药球'
          },
          {
            id:208,
            value:'瑞士球'
          },
          {
            id:209,
            value:'波速球'
          },
          {
            id:210,
            value:'泡沫轴'
          }
        ]
      },
      fixed_appliance:{
        title:'固定器械',
        buttons:[
          {
            id:300,
            value:'全部'
          },
          {
            id:301,
            value:'龙门架'
          },
          {
            id:302,
            value:'史密斯机'
          },
          {
            id:303,
            value:'推胸机'
          },
          {
            id:304,
            value:'悍马机'
          },
          {
            id:305,
            value:'夹胸器'
          },
          {
            id:306,
            value:'划船机'
          },
          {
            id:307,
            value:'下拉机'
          },
          {
            id:308,
            value:'地雷架'
          },
          {
            id:309,
            value:'推肩器'
          },
          {
            id:310,
            value:'倒蹬机'
          },
          {
            id:311,
            value:'哈克机'
          },
          {
            id:312,
            value:'腿弯举机'
          },
          {
            id:313,
            value:'腿屈伸机'
          },
          {
            id:314,
            value:'提踵机'
          },
          {
            id:315,
            value:'单杠'
          },
          {
            id:316,
            value:'双杠'
          },
          {
            id:317,
            value:'仰卧板'
          },
          {
            id:318,
            value:'罗马椅'
          },
          {
            id:319,
            value:'牧师凳'
          },
          {
            id:320,
            value:'台阶机'
          },
          {
            id:321,
            value:'动感单车'
          },
          {
            id:322,
            value:'椭圆机'
          },
          {
            id:323,
            value:'跑步机'
          }
        ]
      },
      unarmed_training:{
        title:'徒手训练',
        buttons:[
          {
            id:400,
            value:'全部'
          }
        ]
      }
    }
  },
  training_target:{
    title:'训练目标',
    details:{
      training_target:{
        title:'',
        buttons:[
          {
            id:500,
            value:'不限目标'
          },
          {
            id:501,
            value:'增肌'
          },
          {
            id:502,
            value:'减脂'
          },
          {
            id:503,
            value:'塑型'
          },
          {
            id:504,
            value:'拉伸'
          }
        ]
      }
    }
  },
  training_type:{
    title:'训练级别',
    details:{
      training_type:{
        title:'',
        buttons:[
          {
            id:600,
            value:'不限级别'
          },
          {
            id:601,
            value:'初级'
          },
          {
            id:602,
            value:'中级'
          },
          {
            id:603,
            value:'高级'
          }
        ]
      }
    }
  }
};
